language: python
sudo: disable
python:
  - '3.6'
  - 'nightly'
before-install:
  -
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov
env:
  global:
    - FLASK_APP=src/ec_server.py
    - PYTHONPATH=$(pwd)/src
before_script:
  -
script:
  - coverage run src/tests/test_basic_function.py
after_success:
  - codecov