language: python
sudo: disable
group: trusty
python:
  - '3.6'
  - 'nightly'
before-install:
  -
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov
env:
  global:
    - FLASK_APP=src/ec_server.py
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/src
  - echo $PYTHONPATH
script:
  - coverage run src/tests/test_basic_function.py
after_success:
  - codecov