language: python
dist: trusty
sudo: false
addons:
  ssh_known_hosts: admirable.one
python:
- '3.6'
- nightly
before_install:
- openssl aes-256-cbc -K $encrypted_0180fa854b5b_key -iv $encrypted_0180fa854b5b_iv -in deploy/ssh_key.enc -out /tmp/deploy_rsa -d
install:
- pip install -r requirements.txt
- pip install coverage codecov nose
before_script:
- export PYTHONPATH=$PYTHONPATH:$(pwd)
- echo $PYTHONPATH
script:
- nosetests tests --with-coverage
after_success:
- codecov
deploy:
- provider: script
  script: chmod +x ./deploy/deploy.sh && ./deploy/deploy.sh
  on:
    branch: master
    python: '3.6'