language: python
sudo: disable
python:
  - '3.6'
  - 'nightly'
before-install:
  -
install:
  - pip install -r requirements.txt
env:
  global:
    - FLASK_APP=src/ec_server.py
before_script:
  -
script:
  - flask test
after_success: