language: python
dist: trusty
sudo: false
addons:
  ssh_known_hosts: admirable.one
python:
- '3.6'
- nightly
before_install:
- openssl aes-256-cbc -K $encrypted_0180fa854b5b_key -iv $encrypted_0180fa854b5b_iv -in deploy/ssh_key.enc -out /tmp/deploy_key -d
- openssl aes-256-cbc -K $encrypted_1287f26e886e_key -iv $encrypted_1287f26e886e_iv -in deploy/stage_key.enc -out /tmp/stage_key -d
- chmod +x deploy/deploy.sh
install:
- pip install -r requirements/dev.txt
before_script:
- export PYTHONPATH=$PYTHONPATH:$(pwd)
- echo $PYTHONPATH
script:
- nosetests tests --with-coverage
after_success:
- codecov
- echo $(pwd)
deploy:
- provider: script
  script: bash deploy/deploy.sh
  on:
    branch: master
    python: '3.6'
- provider: script
  script: bash deploy/deploy.sh
  on:
    branch: develop
    python: '3.6'