language: python
dist: trusty
sudo: false
python:
  - '3.6'
  - 'nightly'
before-install:
  -
install:
  - pip install -r requirements.txt
  - pip install coverage codecov nose
env:
  global:
    - FLASK_APP=ec_server.py
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - echo $PYTHONPATH
script:
  - nosetests src/tests --with-coverage
after_success:
  - codecov