language: python
sudo: disable
addons:
  apt:
    packages:
      - python-dev
      - libssl-dev
      - libffi-dev
python:
  - '3.6'
  - 'nightly'
before-install:
  -
install:
  - pip install -r requirements.txt
env:
  -
before_script:
  -
script:
  - flask test
after_success: